from __future__ import annotations

from comm_ls.cl_v32_strategy import (
    SHIPPING_ACCEL_FEATURE,
    SHIPPING_MOMENTUM_FEATURE,
    SleeveConfig,
    validate_config,
)


CL_V41_MAX_SINGLE_NAME_WEIGHT = 0.05


# Source of truth: notebooks/backtest_cl_v41.ipynb as executed on 2026-08-19.
# Several executed position transformations differ from the descriptive config
# cell in that notebook; the values below follow the executed cells.
CL_V41_SLEEVE_CONFIG: dict[str, SleeveConfig] = {
    "psx_ref": SleeveConfig(
        weight=0.05,
        tickers=("PSX",),
        feature_symbol="CL",
        feature="activity_deferred_annualized_carry_chg_21d",
        threshold=0.01,
        side_mult=1,
        position_mode="rolling_fixed_hold",
        hold_days=3,
        rolling_days=5,
        sector_hedge="XLE",
        internal_weights={"PSX": 1.0},
    ),
    "refiner": SleeveConfig(
        weight=0.10,
        tickers=("DINO", "DK", "PBF"),
        feature_symbol="HO",
        feature="front_third_annualized_carry_chg_21d",
        threshold=0.01,
        lower_threshold=-0.02,
        upper_threshold=0.05,
        side_mult=1,
        position_mode="rolling_mean",
        hold_days=None,
        rolling_days=5,
        sector_hedge="XLE",
        internal_weights={"DK": 0.50, "DINO": 0.20, "PBF": 0.30},
        signal_rule="band_hysteresis",
    ),
    "fuel": SleeveConfig(
        weight=0.04,
        tickers=("MUSA", "CASY"),
        feature_symbol="XB",
        feature="front_third_annualized_carry",
        threshold=0.06,
        side_mult=-1,
        position_mode="fixed_hold",
        hold_days=5,
        rolling_days=None,
        sector_hedge=None,
        internal_weights={"MUSA": 0.40, "CASY": 0.60},
        combined_share_rounding=True,
    ),
    "services": SleeveConfig(
        weight=0.05,
        tickers=("SLB", "HAL", "FTI"),
        feature_symbol="CL",
        feature="jun_dec_annualized_carry_v2",
        threshold=1.0,
        side_mult=1,
        position_mode="sign",
        hold_days=None,
        rolling_days=None,
        sector_hedge="XLE",
        internal_weights={"SLB": 0.40, "HAL": 0.20, "FTI": 0.40},
        signal_rule="service_asymmetric_z",
        feature_scale="z",
    ),
    "shipping": SleeveConfig(
        weight=0.25,
        tickers=("DHT", "FRO", "TNK", "STNG", "INSW"),
        feature_symbol="CL",
        feature="carry",
        threshold=0.01,
        side_mult=-1,
        position_mode="rolling_mean",
        hold_days=None,
        rolling_days=2,
        sector_hedge="XLE",
        internal_weights={
            "DHT": 0.30,
            "FRO": 0.30,
            "TNK": 0.15,
            "STNG": 0.05,
            "INSW": 0.20,
        },
        signal_rule="shipping_sticky_accel",
        auxiliary_features=(SHIPPING_MOMENTUM_FEATURE, SHIPPING_ACCEL_FEATURE),
    ),
    "chemical": SleeveConfig(
        weight=0.28,
        tickers=("AVNT", "CE", "DOW", "EMN", "HUN", "LYB", "WLK"),
        feature_symbol="CL",
        feature="carry",
        threshold=0.02,
        side_mult=1,
        position_mode="fixed_hold",
        hold_days=21,
        rolling_days=None,
        sector_hedge="XLE",
        internal_weights={
            "AVNT": 0.05,
            "CE": 0.10,
            "DOW": 0.20,
            "EMN": 0.10,
            "HUN": 0.10,
            "LYB": 0.25,
            "WLK": 0.20,
        },
        signal_rule="chemical_inflection",
    ),
    "metals": SleeveConfig(
        weight=0.05,
        tickers=("ATI", "CRS", "HWM"),
        feature_symbol="CL",
        feature="next_dec_annualized_carry_gap_le_9m_v2",
        threshold=0.015,
        side_mult=-1,
        position_mode="fixed_hold",
        hold_days=10,
        rolling_days=None,
        sector_hedge="XME",
        internal_weights={"ATI": 0.40, "CRS": 0.30, "HWM": 0.30},
        signal_rule="asymmetric_hysteresis",
    ),
    "bwt": SleeveConfig(
        weight=0.06,
        tickers=("ERO", "TECK"),
        feature_symbol="CL",
        feature="brent_wti_carry_spread",
        threshold=0.02,
        side_mult=-1,
        position_mode="fixed_hold",
        hold_days=3,
        rolling_days=None,
        sector_hedge="XME",
        internal_weights={"ERO": 0.75, "TECK": 0.25},
        signal_rule="asymmetric_hysteresis",
    ),
}


validate_config(CL_V41_SLEEVE_CONFIG)

